// Twinion Map Script Equates

#define MapEventTypeEncounter		0
#define MapEventTypeFaceLook		1
#define MapEventTypeFaceStep		2
#define MapEventTypeTileArrive		3
#define MapEventTypeUseItem			4
#define MapEventTypeUseSkillSpell	5

#define FlagTypeTile				0
#define FlagTypeMap					1
#define FlagTypeDungeon				2
#define FlagTypParty				2

#define DirectionNorth				0
#define DirectionEast				1
#define DirectionSouth				2
#define DirectionWest				3

// === Skill indexes =========================================================================================
// ===========================================================================================================

#define SKILL_ATHLETICS         0
#define SKILL_CLUBS_AND_AXES    1
#define SKILL_BERSERKER         2
#define SKILL_PURSUIT           3

#define SKILL_LEADERSHIP        4
#define SKILL_SWORDSMANSHIP     5
#define SKILL_BINDING           6
#define SKILL_INTIMIDATE        7

#define SKILL_ARCHERY           8
#define SKILL_STAMINA           9
#define SKILL_FURTIVENESS       10
#define SKILL_READ_TRACKS       11

#define SKILL_BARD              12
#define SKILL_DETECT            13
#define SKILL_LOCKPICK          14
#define SKILL_PICKPOCKET        15

#define SKILL_MARTIAL_ARTS      16
#define SKILL_DEFLECT_MAGIC     17
#define SKILL_MEDIC             18
#define SKILL_REVERIE           19

#define SKILL_RUNE_READING      20
#define SKILL_STAFF             21
#define SKILL_CHANNEL           22
#define SKILL_DEEP_TRANCE       23

#define MANA_RESTORE            24

// === Spell indexes =========================================================================================
// ===========================================================================================================

#define SPELL_BACKFIRE          0
#define SPELL_BLAST             1
#define SPELL_CONTROL           2
#define SPELL_CURSE             3
#define SPELL_DEATH_DARTS       4
#define SPELL_DISSIPATE         5
#define SPELL_FIREBALL          6
#define SPELL_HAIL              7
#define SPELL_LIGHTNING         8
#define SPELL_PETRIFY           9
#define SPELL_POISON_CLOUD      10
#define SPELL_STORM_WIND        11

#define SPELL_AURA              12
#define SPELL_SHROUD_OF_LIGHT   13
#define SPELL_ENERGY_FIELD      14
#define SPELL_SHIELD            15

#define SPELL_REFRESH           16
#define SPELL_TELEPORT          17
#define SPELL_BLESS             18
#define SPELL_CURE              19
#define SPELL_HEAL              20
#define SPELL_RESIST            21
#define SPELL_RESUSCITATE       22
#define SPELL_TRUE_SEEING       23

// === Item Indexes ==========================================================
// ===========================================================================

#define NULLITEM 0
#define SHORTSWORD 1
#define BROADSWORD 2
#define LONGSWORD 3
#define HEAVENSWRATH 4
#define FLAMEBLADE 5
#define CRYSTALIZEDBLADE 6
#define FROSTBLADE 7
#define IRONCUTLASS 8
#define KATANA 9
#define SAMURAISWORD 10
#define SILVERSWORD 11
#define BLACKBLADE 12
#define SERPENTSFANG 13
#define THIEFSSTILETTO 14
#define FLAMETONGUE 15
#define TWOHANDEDSWORD 16
#define PHOSPHORESCENTBLADE 17
#define AXE 18
#define BATTLEAXE 19
#define WOODSMANSAXE 20
#define BRONZEBATTLEAXE 21
#define MERCURYAXE 22
#define AXEOFVENOM 23
#define BARBARIANAXE 24
#define DEATHSCLEAVER 25
#define CLUB 26
#define MACE 27
#define STONECLUB 28
#define MORNINGSTAR 29
#define HEARTFLAIL 30
#define NUNCHUKAS 31
#define NINJASTICKS 32
#define PEACEMAKER 33
#define FLAIL 34
#define HOLLOWEDNUNCHUKAS 35
#define SOLDIERSFLAIL 36
#define WARHAMMER 37
#define HAMMEROFMIGHT 38
#define WRATHOFFAITH 39
#define STONEGIANTSHAMMER 40
#define GAUNTLETSOFMERCY 41
#define GLOVESOFPROTECTION 42
#define QUARTERSTAFF 43
#define SPEAR 44
#define MANDRAKESTAFF 45
#define HALBERD 46
#define KINGSLANCE 47
#define LIGHTNINGROD 48
#define RODOFMERCY 49
#define STAFFOFGIANTS 50
#define LANCEOFDARKNESS 51
#define POLEARM 52
#define BARDICHE 53
#define STAFFOFJUSTICE 54
#define DIVININGROD 55
#define LANCE 56
#define ARNAKKIANSSTAFF 57
#define RODOFTHESERPENT 58
#define RODOFRESONANCE 59
#define STAFFOFTHEMAGUS 60
#define TIMESSCYTHE 61
#define DISRUPTOR 62
#define VORANTISGAUNTLETS 63
#define SHORTBOW 64
#define LONGBOW 65
#define SILVERBOW 66
#define CROSSBOW 67
#define COMPOSITEBOW 68
#define STORMSBOW 69
#define GLASSBOW 70
#define BOWOFFLAMES 71
#define CRESCENTMOON 72
#define LONGBOWOFLEGEND 73
#define TWINBOLTS 74
#define DEGREEOFVENGEANCE 75
#define ARCHEDDEATH 76
#define BUCKLER 77
#define ROUNDSHIELD 78
#define BLOODSHIELD 79
#define ICESHIELD 80
#define OBLONGSHIELD 81
#define WINGEDSHIELD 82
#define HARMSWAY 83
#define SILVERAEGIS 84
#define AEGISDDRACO 85
#define SKULLAEGIS 86
#define CHAOSGUARDIAN 87
#define HARMONYSGUARDIAN 88
#define PLATINUMBUCKLER 89
#define MIDNIGHTAEGIS 90
#define KNIGHTSSHIELD 91
#define SPIKEDSHIELD 92
#define AEGISOFMIGHT 93
#define LEATHERCAP 94
#define HEADCHAINMAIL 95
#define WARHAT 96
#define SOVEREIGNCROWN 97
#define MEDITATIONCAP 98
#define SCRIBESSALLET 99
#define HELMET 100
#define IRONCROWN 101
#define WINGEDSALLET 102
#define SPIDERSILKHELM 103
#define HELMOFWISDOM 104
#define TRACKERSMASK 105
#define BASINET 106
#define BARBARIANSHELM 107
#define NIGHTELFHELM 108
#define DAWNSHEADPIECE 109
#define VALKYRIESHELM 110
#define HELMOFGUILE 111
#define ARNAKKIANSCAP 112
#define JESTERSCAP 113
#define CLOTHJACKET 114
#define LEATHERJACKET 115
#define CHAINMAIL 116
#define SACKCLOTHJACKET 117
#define BREASTPLATE 118
#define BARBARIANSPLATE 119
#define KNIGHTSBREASTPLATE 120
#define RANGERSCHAINMAIL 121
#define THIEFSJACKET 122
#define CLERICSCHAINMAIL 123
#define WIZARDSSASH 124
#define SNAKESKINJACKET 125
#define MAILOFTHEMAGUS 126
#define ETHERICVESTMENT 127
#define SHADOWCLOAK 128
#define PRIESTLYGARB 129
#define WIZARDSROBES 130
#define PLATEOFIRON 131
#define DRAGONSSKIN 132
#define GRANITEARMOR 133
#define JEWELEDBREASTPLATE 134
#define THIEFSCLOAK 135
#define TEMPEREDADAMANTINE 136
#define SPIRITUALARMOR 137
#define BERSERKERTALISMAN 138
#define BINDINGTALISMAN 139
#define READTRACKSTALISMAN 140
#define TRANCETALISMAN 141
#define FREEDOMRING 142
#define JADEDRING 143
#define RINGOFTHIEVES 144
#define IRONRING 145
#define NEROSLYRE 146
#define THIEVESFLUTE 147
#define STONEOFTHEMAGI 148
#define SCORCHEDSTONE 149
#define MIRROREDGEMSTONE 150
#define PRIESTSAMULET 151
#define DRAGONSSTONE 152
#define PIPESOFENCHANTMENT 153
#define SISYPHUSSTONE 154
#define AMULETOFPROTECTION 155
#define HALOSCROLL 156
#define SCROLLOFPROTECTION 157
#define REFRESHSCROLL 158
#define SCROLLOFTHESUN 159
#define CURSEDSCROLL 160
#define BASALTSCROLL 161
#define RUNECHART 162
#define HAWKSEYE 163
#define CRYSTALBALL 164
#define SHAMANSCROLL 165
#define SCROLLOFDEATH 166
#define LIFEGIVER 167
#define AURASCROLL 168
#define BOOMERANGSCROLL 169
#define PUMMELSCROLL 170
#define ZEUSSCROLL 171
#define SOVEREIGNSCROLL 172
#define SYMBOLOFDEATH 173
#define SCROLLOFSAFETY 174
#define SCORCHEDSCROLL 175
#define CRYSTALSCROLL 176
#define BLOODSCROLL 177
#define REFRESHALLSCROLL 178
#define SHIELDINGSCROLL 179
#define SCROLLOFWIND 180
#define HEALPOTION 181
#define ELIXIROFHEALTH 182
#define HEALALLPOTION 183
#define HEALAMPHORA 184
#define TELEPORTPASS 185
#define SILVERBAR 186
#define GOLDBAR 187
#define PLATINUMBAR 188
#define SLIVERBAR 189
#define GREENLOCKPICK 190
#define REDLOCKPICK 191
#define BLUELOCKPICK 192
#define CUREPOTION 193
#define CURATIVEELIXIR 194
#define CUREALLPOTION 195
#define BLESSPOTION 196
#define RESUSCITATOR 197
#define HOPESFURY 198
#define CARISSASGAUNTLETS 199
#define LAVAGLOVE 200
#define ICEFLAME 201
#define FLASKOFSHADOWFALL 202
#define MANAPOTION 203
#define MANAELIXIR 204
#define MANARESTORE 205
#define MANAAMPHORA 206
#define STONEOFAWARENESS 207
#define SKELETONKEY 208
#define LUMINOUSLANTERN 209
#define MAZEKEY 210
#define SLATEMAP 211
#define PARCHMENTMAP 212
#define LEATHERMAP 213
#define SNAKESKINMAP 214
#define SNAKECHARM 215
#define FELLOWSHIPKEY 216
#define TNEPRESKEY 217
#define DIAMONDLOCKPICK 218
#define EMERALDLOCKPICK 219
#define SAPPHIRELOCKPICK 220
#define RUBYLOCKPICK 221
#define FRONTDOORKEY 222
#define KEYOFC 223
#define ROPE 224
#define LIFEJACKET 225
#define CORAL 226
#define TOPAZ 227
#define PEARL 228
#define EBONY 229
#define OPAL 230
#define SPIRITBOTTLE 231
#define PRICELESSBAR 232
#define DRALKARIANRING 233
#define QUEENSKEY 234
#define WHOLEMAP 235
#define JUICYDRAGONSTEAK 236
#define FUNHOUSEKEY 237
#define NIMBUSOFTHEFATES 238
#define REALITYSRAMPART 239
#define STARBURST 240
#define CROSSKEY 241
#define BRASSRING 242
#define SWORDOFARES 243
#define GAEASFLAIL 244
#define NEPTUNESTRIDENT 245
#define BOWOFEOS 246
#define EYEOFCIRCINUS 247
#define EASTEREGG 248
#define STATUEOFSTORMGIANT 249
#define NAOMISKEY 250
#define HACKSAWBLADE 251
#define HANDSOFTHEMAGI 252
#define RODOFDISSEMINATION 253
#define UNITYRING 254

// === Map Flag Indexes ======================================================================================
// ===========================================================================================================
        
#define DEEPPORTALS 0
#define DRAKSPORT 1
#define FIRSTQUEST 2
#define UPPERROPE 3
#define NPCGIFTONE 4
#define I_QUEST_RIGHT 6
#define I_QUEST_LEFT 7
#define GOTSCAR 8
#define ONE_AND_THREE_DONE 9
#define KILLEDAQUEUS 10
#define LEARNEDCHANT 11
#define LEARNEDRHYME 12
#define METJUBILAH 13
#define KILAM 14
#define SETDUCTSWITCH 15
#define DIDPATH 16
#define CROSSBRIDGE 17
#define QUADRANTA 18
#define QUADRANTB 19
#define QUADRANTC 20
#define QUADRANTD 21
#define ALLQUADS 22
#define TOTAL 23
#define ARENASTASHA 24
#define ARENASTASHB 25
#define ARENASTASHC 26
#define ARENASTASHD 27
#define ITEMTOTAL 28
#define HINTEDATDOOR 29
#define DIDFIREBALL 30
#define WHATWEAPON 31
#define FINISHEDGAME 32
#define DONEPROVING 33
#define DIDUPPERRIGHT 34
#define DIDMIDDLEUP 35
#define DIDMIDDLELOW 36
#define DIDLOWERRIGHT 37
#define KNOWSALL 38
#define LEARNEDDWARF 39
#define LEARNEDELF 40
#define LEARNEDGNOME 41
#define LEARNEDORC 42
#define LEARNEDTROLL 43
#define LEARNEDHALF 44
#define LEARNEDGREMLIN 45
#define LEARNEDHUMAN 46
#define DIDJOKEPAIR 47
#define SAVEDPARTY 48
#define KILLMONSTERG 49
#define CHAOSPUNISH 50
#define KILLMONSTERF 51
#define HARMONYPUNISH 52
#define UNITYRINGONE 53
#define UNITYRINGTHREE 54
#define UNITYRINGTWO 55
#define UNITYRINGDAMAGE 56
#define CHOR_NPC_KILLED 57
#define CHOR_KNOWN 58
#define DIDPATHWAY 59
#define PATHWAYDONE 60
#define SNOWY 61
#define LABY_ONE_GOLD 62
#define SNICKER 63
#define WINDY 64
#define MISTY 65
#define SLATE_MAP 66
#define CHAOS_MAZE 67
#define HARMONY_MAZE 68
#define ARMORY_ITEM 69
#define TRIDENT 70
#define JACKET 71
#define HERBAL 72
#define PARCHMENT_MAP 73
#define VAULT 74
#define CART_FOUR 75
#define CART_THREE 76
#define CART_TWO 77
#define CART_ONE 78
#define NSTAR 79
#define SPIRIT 80
#define LEATHER_MAP 81
#define UNIVERSAL 82
#define TRACK 83
#define TNEPRES 84
#define SNAKESKIN_MAP 85
#define ROPE_FLAG 86
#define RUBY 87
#define SCALE 88
#define INSTRUCTOR 89
#define ALCHEMY 90
#define ARMORY 91
#define GENERAL 92
#define MAGIC_SHOP 93
#define HOCUS_GOLD 94
#define HOCUS_SCROLL 95
#define HOCUS_SPELL 96
#define HOCUS_SKILL 97
#define HOCUS_MAZE 98
#define GRIMOIRE 99
#define TOKEN_ONE 100
#define TOKEN_TWO 101
#define TOKEN_THREE 102
#define BROKEDOOR 103
#define WINNER 106
#define CHOR_NAOMI_MET 107
#define CHOR_BOOTY 108
#define CHOR_CONTROL_1 110
#define WHICHPIECE 111
#define SWITCHESSET 112
#define POOLNUMBER 113
#define DIDASTRAL 114
#define GOTASTRALITEM 116
#define GOTPHYSITEM 117
#define SPOKEWITHGRATOK 119
#define HOCUS_DONE 120
#define GAVE_INFO 121
#define LORDGNOG 122
#define KILLEDPRAXIS 123
#define KILLEDEREBUS 124
#define GUARDIAN 126
#define AMPHORAENCS 127
#define LAVAQUEST 128
#define BATCAVE 130
#define MERCHANT 131
#define FNTN 132
#define RESIST 133
#define EFIELD 134
#define CURSED 136
#define WIZSPELL 137
#define THIEFBOOTY 138
#define WIERDO 139
#define KILLEDCORPEUS 140
#define KILLEDASTELLIGUS 141
#define KILLEDJUVALAD 142
#define KILLEDMALOS 143
#define DRAGSTR 144
#define DRAGINI 145
#define DRAGAGI 146
#define DRAGDEF 147
#define GAVEUNITYRING 148
#define GETUNITYRING 149
#define EASTQUESTDONE 150
#define NPCKEYCLUE 151
#define NPCENDCHAT 152
#define OPENDOORB 153
#define OPENDOORC 154
#define OPENDOORD 155
#define KILLEDPLUTHROS 156
#define FLAMEDOOR 157
#define FTNONOFF 158
#define HEAVENFTNC 159
#define HEAVENFTND 160
#define HEAVENFTNE 161
#define HEAVENFTNONE 162
#define HEAVENFTNTWO 163
#define HEAVENFTNTHREE 164
#define HEAVENFTNFOUR 165
#define HEAVENFTNFIVE 166
#define HEAVENFTNSIX 167
#define THORZIL 168
#define SHADOWFALL 169
#define TB 170
#define TA 171
#define TC 172
#define TD 173
#define GUARD 174
#define DEMONIA 175
#define HELLBATTLE 176
#define HFURY 177
#define IFLAME 178
#define PANHEAL 179
#define PANSCROLL 180
#define PANMANA 182
#define PANMONEY 183
#define PANLIFE 184
#define PANBUCKS 185
#define STORM 189
#define KILLEDQUEEN 190
#define WONTHISGAME 191
#define ONLYONCE 192
#define PHYSFNT 193
#define TOTHEQUEEN 194
#define NICEBOOTY 195
#define ITEMUSES 196
#define TALKED_TO_NPC1 197
#define TALKED_TO_NPC2 198
#define SPELLINGWORD 199
#define SPELLEDBOTH 200
#define TOOKITEM 201
#define WHICHNPC 202
#define FIRST_DOOR_OPEN 203
#define SECOND_DOOR_OPEN 204
#define THIRD_DOOR_OPEN 205
#define DOOR_FLAG_B 206
#define DOOR_FLAG_C 207
#define DOOR_FLAG_D 208
#define GREATBOOTY 209
#define FUN_BAR_COUNT 210
#define SEETHEKNIGHT 211
#define CLERICBACK 212
#define BLESSCLERIC 213
#define BLESSWIZ 214
#define REFRESHCLERIC 215
#define HALLOFDOOM 216
#define WIZFOUNTAIN 218
#define ML_CHOSEWEAPON 219
#define ML_UNLOCKEDFRONTDOOR 220
#define ML_REVEALED_BALLROOM_PATH 221
#define ML_OBTAINED_SNAKE_CHARM 222
#define ENDGAMETELE 223
#define ML_STARBURST_RING 224
#define ML_GLIMPSE_CIRCINUS 225
#define ML_DISSEMINATE_WALL 226
#define SAW_TOOL_SHED 227
